# Generated by Django 4.0 on 2021-12-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='preffession',
            new_name='location',
        ),
        migrations.AddField(
            model_name='contact',
            name='icon',
            field=models.ImageField(null=True, upload_to='uploadslogo'),
        ),
    ]
